### ISSUE TITLE
preprocess data failing for 24M records

### ISSUE THREAD

**Issue by sunishaharish** [ChiragLakhanpal/Capstone#5]
![image](https://github.com/ChiragLakhanpal/Capstone/assets/112507763/131ddea9-e228-45e6-86d9-7494cec524fa)

The data is being read and displayed but the process is getting killed during the preprocessing steps.

**Comment by ChiragLakhanpal** [comment]
@sunishaharish Is it the preprocess.py script?

**Comment by sunishaharish** [comment]
@ChiragLakhanpal Yes it is the same script

**Comment by ChiragLakhanpal** [comment]
@sunishaharish I will try to migrate the code to polars.

**Comment by ChiragLakhanpal** [comment]
@sunishaharish Please check now. I have updated the code to include Polars.
